### ISSUE TITLE
修改配置优化接口响应

### ISSUE THREAD

**Issue by lindadev77** [ZhongFuCheng3y/austin#38]
页面接口列表第一次进来耗时都是2秒多，但是同个页面连续查询，除了第一次，后面都是几毫秒。本地测试的时候通过main()启动项目，debug发现无涉及数据库操作通过校验直接返回的也是两秒多。
下面是通过几处配置的修改将接口响应优化到文档几毫秒返回（还未涉及数据库查询的）比如短信下发数据，58行直接返回。
![image](https://user-images.githubusercontent.com/9762702/236614885-8d6e9aff-8a07-469f-a440-d971b02b653c.png)

1. 升级mysql依赖版本，引入druid连接池管理
   /austin/pom.xml
```
    <properties>
        <druid-spring-boot-starter.version>1.1.22</druid-spring-boot-starter.version>
        <mysql-connector-java.version>8.0.20</mysql-connector-java.version>
    </properties>


    <dependencyManagement>
           <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>${mysql-connector-java.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>${druid-spring-boot-starter.version}</version>
            </dependency>
    </dependencyManagement>
```
   /austin/austin-support/pom.xml 添加
```
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
        </dependency>
```
3. 修改项目工程配置，数据库连接添加druid相关配置
/austin/austin-web/src/main/resources/application-dev.yml
```
spring:
  datasource:
    name: austin
    url: jdbc:mysql://127.0.0.1:3306/austin?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: ${austin.database.username:root}
    password: ${austin.database.password:123456}
    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 200
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxOpenPreparedStatements: 2
```

优化前
![image](https://user-images.githubusercontent.com/9762702/236615366-83ef964a-9942-4756-8a28-d3214c1fcee7.png)

看下优化后的接口响应
![image](https://user-images.githubusercontent.com/9762702/236614695-5d7d300f-2ce8-49fb-9769-295f9e907a25.png)
